# Generated by Django 4.1 on 2023-12-15 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_data_dataset_id_data_img_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="token",
            new_name="password_md5",
        ),
    ]
