# Generated by Django 4.1 on 2023-12-15 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_datasets_dataset_dataset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="data",
        ),
    ]
