# Generated by Django 5.0.2 on 2024-02-16 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_explore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explore',
            options={},
        ),
        migrations.AlterField(
            model_name='explore',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='explore',
            name='post_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='explore',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_posts', to='home.explore'),
        ),
    ]
