# Generated by Django 5.0.2 on 2024-02-20 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_explore_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('weather', models.CharField(blank=True, choices=[('sunny', '晴朗'), ('cloudy', '多云'), ('rainy', '雨天'), ('snowy', '雪天')], max_length=20, null=True)),
                ('mood', models.CharField(blank=True, choices=[('happy', '开心'), ('sad', '伤心'), ('angry', '生气'), ('calm', '平静')], max_length=50, null=True)),
                ('background', models.CharField(blank=True, choices=[('work', '工作'), ('vacation', '假期'), ('home', '家中'), ('outdoors', '户外')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='home.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.subcategory')),
            ],
        ),
    ]
