# Generated by Django 5.0.2 on 2024-02-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('tshirts', 'T-shirts')], max_length=100),
        ),
    ]
