# Generated by Django 5.0.2 on 2024-02-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_item_category_alter_item_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('lyric', models.TextField(blank=True)),
                ('sublyric', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('科普', '科普'), ('问卷', '问卷'), ('方案', '方案')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.CharField(choices=[('成瘾问题', '成瘾问题'), ('焦虑心理', '焦虑心理'), ('恋爱相关', '恋爱相关'), ('强迫症', '强迫症'), ('适应障碍', '适应障碍'), ('睡眠障碍', '睡眠障碍'), ('抑郁心理', '抑郁心理'), ('自我认知障碍', '自我认知障碍')], max_length=100),
        ),
    ]
