# Generated by Django 5.0.2 on 2024-02-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_music_alter_item_category_alter_item_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='poster',
            field=models.ImageField(upload_to='static/data/pictures', verbose_name='图片路径'),
        ),
    ]
