# Generated by Django 5.0.2 on 2024-02-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_music_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='poster',
            field=models.ImageField(upload_to='static/', verbose_name='图片路径'),
        ),
    ]
