# Generated by Django 5.0.2 on 2024-02-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_music_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='background',
            field=models.CharField(blank=True, choices=[('milktea', '奶茶'), ('cat', '猫猫'), ('dragon', '龙龙'), ('dish', '吃饭')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', '晴朗'), ('cloudy', '多云'), ('overcast', '阴'), ('sprinkle', '小雨'), ('rain', '雨'), ('thunderstorm', '暴雨雨'), ('snow', '雪'), ('fog', '雾'), ('tornado', '龙卷风'), ('smog', '雾霾'), ('sangstorm', '沙尘暴')], max_length=20, null=True),
        ),
    ]
