# Generated by Django 5.0.2 on 2024-02-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_diary_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='weather',
            field=models.CharField(blank=True, choices=[('晴朗', '晴朗'), ('多云', '多云'), ('阴', '阴'), ('小雨', '小雨'), ('雨', '雨'), ('暴雨', '暴雨'), ('雪', '雪'), ('雾', '雾'), ('龙卷风', '龙卷风'), ('雾霾', '雾霾'), ('沙尘暴', '沙尘暴')], max_length=20, null=True),
        ),
    ]
