# Generated by Django 5.0.2 on 2024-02-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_diary_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='background',
            field=models.CharField(blank=True, choices=[('默认', '默认'), ('奶茶', '奶茶'), ('猫猫', '猫猫'), ('龙龙', '龙龙'), ('吃饭', '吃饭')], max_length=100, null=True),
        ),
    ]
