# Generated by Django 4.1 on 2024-03-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_questionnaire_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option1', to='home.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option2', to='home.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option3', to='home.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option4', to='home.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option5', to='home.option'),
        ),
    ]
