# Generated by Django 4.1 on 2024-03-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_question_option1_question_option2_question_option3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
    ]
