# Generated by Django 4.1 on 2024-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
