# Generated by Django 4.1 on 2024-03-17 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_questionnaire_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option6', to='home.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option7', to='home.option'),
        ),
    ]
